### ISSUE TITLE
Strange line breakage

### ISSUE THREAD

**Issue by 2n** [swhitty/SwiftDraw#8]
This library helps me every day. Thank you so much.

I have tried to convert Feather icons using version 0.9.5.
Almost everything was converted correctly, but I could see a strange line breakage in "key.svg".
![swiftdraw_key](https://user-images.githubusercontent.com/52402075/182675946-221ec62a-d52c-4745-9216-92379e10913b.png)

I'm not sure if the problem is with the file or the library, but at least this SVG file shows up correctly in the macOS Finder and other graphics tools.

The link to key.svg is here.
https://feathericons.com/?query=key

**Comment by swhitty** [comment]
Thank you for the bug report @2n.

This is now fixed in the[ 0.9.6](https://github.com/swhitty/SwiftDraw/releases/tag/0.9.6) release.

There was a bug in how the path position was calculated when a path includes broken segments (multiple moves). Fix [here](https://github.com/swhitty/SwiftDraw/commit/abd0f23ac0038130d25d1ab368acd39ec7712d12)

**Comment by 2n** [comment]
Thanks for the quick bug fix!
It works perfectly now.
